version : "3"

services:
  jogatina:
    image: servnoticias
    build: .
    volumes:
      - "./servicos/jogatina:/servicos"
    command: python3 noticias.py
    ports:
      - "5001:5000"

  sistemas:
    image: servnoticias
    build: .
    volumes:
      - "./servicos/sistemas:/servicos"
    command: python3 noticias.py
    ports:
      - "5002:5000"

  banco_jogatina:
    image: memcached
    hostname: banco_jogatina
    ports:
      - "5003:11211"

  banco_sistemas:
    image: memcached
    hostname: banco_sistemas
    ports:
      - "5004:11211"